# Generated by Django 3.1.7 on 2021-03-28 05:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('address', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
