# Generated by Django 3.1.7 on 2021-03-28 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.device'),
            preserve_default=False,
        ),
    ]
